# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: custom-app
#   labels:
#     app: app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: app
#   template:
#     metadata:
#       labels:
#         app: app
#     spec:
#       containers:
#       - name: app-container
#         image: saianilkumardeyyalaa/mysql-create-db-user-app
#         imagePullPolicy: IfNotPresent
#         envFrom:
#         - configMapRef:
#             name: app-config
#         ports:
#         - containerPort: 5000
#         resources:
#           limits:
#             memory: "256Mi"
#             cpu: "500m"
#           requests:
#             memory: "128Mi"
#             cpu: "250m"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: custom-app-service
# spec:
#   ports:
#   - port: 5000
#     targetPort: 5000
#   selector:
#     app: app
#   type: NodePort
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: app-config
# data:
#   DB_HOST: mysql
#   DB_USER: customapp-user
#   DB_PASSWORD: custompassword
#   DB_NAME: customapp-db
#   DB_PORT: "3306"
